### PR TITLE
Update quiz1.md

### PR DESCRIPTION
**Pull request by randerson112358**
Hi, 

I really like what you are doing here and thought I would help. This is actually my first pull request.

My Changes/Fixes:
1) I have added a comma ',' to get back the first two rows of the CSV file, and added an alternative way to get the first two rows.

2) I saw you had nrows(quiz_data), I just deleted the 's' at the end to get nrow(quiz_data)

3) I added quotes to quiz_data[47, Ozone] to get quiz_data[47, 'Ozone']

4) I added the option to show more columns although it isn't really necessary, but I think it would be good for people learning R.

### CODE REVIEW

**Comment by mGalarnyk** [comment]
Hey! 

Excellent fixes to quiz1. I like that you added the option to show more columns since the purpose of this repository is to help people learning R. 

Congrats on your first pull request and congrats on your first merge. Want me to add you as a collaborator to this repository?

**Comment by randerson112358** [comment]
Yes, please and thank you.

On Tue, May 30, 2017 at 12:52 PM, Michael Galarnyk <notifications@github.com

**Comment by mGalarnyk** [comment]
I also subscribed to your youtube channel and added a link to it on the main readme for this repo.
https://github.com/mGalarnyk/datasciencecoursera/blob/master/README.md

I will add it to the rest of the README.md files in the individual course repos later today.

**Comment by randerson112358** [comment]
Wow thanks !

**Comment by MounierLis** [comment]
Comment from GITHUB_TOKEN user

**Comment by MounierLis** [comment]
Comment from GITHUB_TOKEN user

**Comment by MounierLis** [comment]
Comment from GITHUB_TOKEN user

**Comment by MounierLis** [comment]
Comment from GITHUB_TOKEN user

**Comment by NahiaGorrichon** [comment]
Comment from GITHUB_TOKEN user

**Comment by NahiaGorrichon** [comment]
Comment from GITHUB_TOKEN user

**Pull request merged**
